language: node_js
node_js:
  - "6.10.3"
group: deprecated-2017Q3
script: npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codeclimate-test-reporter < lcov.info
